// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlhhmbbshpvgrwbchpbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsaGhtYmJzaHB2Z3J3YmNocGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4Mzg2NzQsImV4cCI6MjA2NDQxNDY3NH0.OLQzuWC8uhTHgL2qDRiOhAgR2jSWrS5CHoaQBIEfdpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);